FROM golang:1.24.11-bookworm AS build
WORKDIR /src
COPY . .
ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -buildvcs=false -trimpath -ldflags='-s -w' \
    -o /out/space-compute-mission-planner ./cmd/space-compute-mission-planner

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/space-compute-mission-planner /usr/local/bin/space-compute-mission-planner
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/space-compute-mission-planner"]
